### ISSUE TITLE
百度网盘链接提取码错误

### ISSUE THREAD

**Issue by hu120051** [Wanghui-Huang/cquOPEN#4]
https://github.com/Wanghui-Huang/cquOPEN/blob/master/README.md
初始资料-获取方式中，[百度网盘](https://pan.baidu.com/share/init?surl=3jUukvf2iMQbP2AM1VmqaA) 链接提取码:baat 错误

**Comment by Wanghui-Huang** [comment]
已更新，请查看：
链接: https://pan.baidu.com/s/11gW-USczyBNoR1Yj9gevNQ 提取码: nvwe

**Comment by hu120051** [comment]
文件已失效，并且md文件中'链接'二字加入到了括号中

**Comment by Wanghui-Huang** [comment]
很可惜，被百度屏蔽了，只能一个个子文件分享（而且部分依旧会失效，建议花几块钱去咸鱼买最新课程吧）：
1. 专业课：链接：https://pan.baidu.com/s/1tdqFsDE-NjgedP9pqJvXUQ 
提取码：2021 
2. 政治：链接：https://pan.baidu.com/s/1ZU_m9Q8vE8DqSrWUJIIxow 
提取码：2021 
3. 英语：链接：https://pan.baidu.com/s/1pGcrD5FG501fXjyKnwc93g 
提取码：2021 
4. 数学：链接：https://pan.baidu.com/s/1W7DKgkgvuC35UmJQKQNGXg 
提取码：2021 
5. 答题卡：链接：https://pan.baidu.com/s/16M-kRn_2JedssUe-FTxCnA 
提取码：2021

**Comment by hu120051** [comment]
非常感谢！
